In [1]:
import pandas as pd
import numpy as np

In [9]:
from scipy import stats
from scipy.stats import norm

In [3]:
cutlet  = pd.read_csv('Cutlets.csv')

In [4]:
cutlet.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [6]:
unitA = pd.Series(cutlet.iloc[:,0])
unitA

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [7]:
unitB = pd.Series(cutlet.iloc[:,1])
unitB

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [8]:
#2sample two tail test

In [10]:
pvalue = stats.ttest_ind(unitA,unitB)
pvalue

TtestResult(statistic=0.7228688704678063, pvalue=0.4722394724599501, df=68.0)

In [11]:
pvalue[1]

0.4722394724599501

# As the pvalue is greater than alpha ,so we fail to reject null hypothesis 
unitA = unitB

# h0=L1=L2=L3=L4
h1=not all are equal

In [12]:
data = pd.read_csv('LabTAT.csv')

In [13]:
data.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [14]:
#Anova ftest

In [15]:
pvalue = stats.f_oneway(data.iloc[:,0],data.iloc[:,1],data.iloc[:,2],data.iloc[:,3])
pvalue

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [16]:
pvalue[1]

2.1156708949992414e-57

# pvalue is too less than alpha(0.05) ,so reject null hypothesis

In [17]:
buyer = pd.read_csv('BuyerRatio.csv')

In [18]:
buyer.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [32]:
buyer_table = buyer.iloc[:,1:6]
buyer_table

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [23]:
chi = stats.chi2_contingency(buyer_table)
chi

Chi2ContingencyResult(statistic=1.595945538661058, pvalue=0.6603094907091882, dof=3, expected_freq=array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [22]:
no_of_rows = len(buyer_table.iloc[0:2,0])
no_of_columns = len(buyer_table.iloc[0,0:4])
DGF=(no_of_rows - 1)*(no_of_columns-1)
print('Degree of freedom',DGF)

Degree of freedom 3


In [24]:
Expected_val = chi[3]

In [25]:
Expected_val

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [26]:
from scipy.stats import chi2
chi_square = sum([(o-e)**2/e for o , e in zip(buyer_table.values,Expected_val)])
chi_square_statistic = chi_square[0] +chi_square[1]
chi_square_statistic

1.5152956451130446

In [27]:
critical_val = chi2.ppf(0.95,3)
critical_val

7.814727903251179

In [28]:
if chi_square_statistic >=critical_val:
    print('Dependent (reject H0)')
else:
    print('Independent(fail to reject H0)')

Independent(fail to reject H0)


In [29]:
pvalue=1-chi2.cdf(chi_square_statistic,3)
pvalue

0.6787446296467897

In [30]:
if pvalue<=0.05:
    print('Dependent (reject H0)')
else:
    print('Independent(fail to reject H0)')

Independent(fail to reject H0)


In [42]:
from scipy.stats import chi2_contingency

In [33]:
cdata = pd.read_csv('Costomer+OrderForm.csv')

In [34]:
cdata.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [39]:
print(cdata['Phillippines'].value_counts(),
      cdata['Indonesia'].value_counts(),
      cdata['Malta'].value_counts(),
      cdata['India'].value_counts())

Error Free    271
Defective      29
Name: Phillippines, dtype: int64 Error Free    267
Defective      33
Name: Indonesia, dtype: int64 Error Free    269
Defective      31
Name: Malta, dtype: int64 Error Free    280
Defective      20
Name: India, dtype: int64


In [40]:
observed = ([[271,267,269,280],[29,33,31,20]])
observed

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [45]:
stat,p,dof,expected = chi2_contingency(observed)

In [46]:
stat

3.858960685820355

In [47]:
p

0.2771020991233135

In [48]:
print('dof=%d' %dof)

dof=3


In [49]:
print(expected)

[[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


In [50]:
alpha = 0.05
prob = 1- alpha
critical = chi2.ppf(prob,dof)
print('probability = %.3f,critical = %.3f,stat = %.3f'%(prob,critical,stat))
if abs(stat) >= critical:
      print('Dependent (reject H0)')
else:
    print('Independent(fail to reject H0)')

probability = 0.950,critical = 7.815,stat = 3.859
Independent(fail to reject H0)


In [51]:
print('significance=%.3f , p=%.3f' %(alpha,p))
if p<=alpha:
      print('Dependent (reject H0)')
else:
    print('Independent(fail to reject H0)')

significance=0.050 , p=0.277
Independent(fail to reject H0)
